services:
  go-test:
    build:
      context: .
      dockerfile: test.Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - 8081:8080
    depends_on:
      - db-test
    environment:
      PORT: 8081
      DATABASE_URL: "postgres://postgres:postgres@:5432/postgres?search_path=public&sslmode=disable"
      DATABASE_DSN: "host=db-test user=postgres password=postgres dbname=postgres port=5432 sslmode=disable"

  db-test:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5434:5432   

  migrate:
    image: arigaio/atlas:latest
    command: >
      migrate apply
      --url "postgres://postgres:postgres@db-test:5432/postgres?search_path=public&sslmode=disable"; tail -f /dev/null
    volumes:
      - ./migrations/:/migrations    
        


  
